createResource:
  defaultSecrets: false
  ingress: true
isOfflineInstallation: false
probeInitialDelaySeconds: 15

ENV_NAME: test
ingressHost: test-epig.k8s-01.konturlabs.com
ingressClass: ingress-nginx
SITE_URL: https://test-apps-ninja01.konturlabs.com/active/
APP_ID: 'c5ecc65b-1e7e-4e31-92a4-222fadeaeef0'
TIMEOUT: 8000
CACHE_TTL: 600
DEBUG: TRUE
#DEFAULT_IMAGE_URL: "https://test-apps-ninja01.konturlabs.com/active/static/assets/preview_screenshot.png"

containers:
  pullSecretName: none
  usePullSecret: false
  chromium_headless:
    replicas: 1
    tag: release-1.4.0.97915b7.1
  preview_generator:
    replicas: 1
    tag: release-1.4.0.97915b7.1
  redis:
    replicas: 1
    tag: "7-alpine3.16"
resources:
  chromium:
    requests:
      cpu: 500m
