apiVersion: v2
name: layers-db-etl
description: A Helm chart for Layers DB ETL

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.107
# don't use appVersion, use {{Values.image.tag}} instead
