{{ if ne .Values.envName "local" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: {{ .Values.envName}}-user-profile-api-platform-pods
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: PlatformPodsUnavailable
      rules:
        - alert: {{ camelcase .Values.envName }}-PlatformPodsUnavailable-UserProfileApi
          annotations:
            message: 'There are {{ "{{$value}}" }} Ready pods in {{ .Values.envName }} UserProfile API'
            summary: There are less Ready pods than required
          expr: |
            kube_deployment_status_replicas_ready{deployment="{{ .Values.envName }}-user-profile-api"}
            < 1
          for: {{ .Values.alertingTime }}
          labels:
            severity: critical
---
{{ end }}