apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/basemap
namePrefix: prod-
namespace: prod-basemap
patches:
  - target:
      kind: HelmRelease
      name: basemap
      group: helm.toolkit.fluxcd.io
      version: v2beta1
    patch: |-
      - op: replace
        path: /spec/chart/spec/valuesFiles
        value:
          - ./helm/basemap/values.yaml
          - ./helm/basemap/values/values-prod.yaml
  - target:
      kind: Deployment
      name: 'prod-basemap-tileserver'
      group: apps
      version: v1
    patch: |-
      - op: add
        path: /spec/template/spec/affinity/nodeAffinity
        value:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - hwn01.k8s-01.kontur.io
---
