apiVersion: v2
name: raster-tiler
description: Helm chart for raster-tiler

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0
# don't use appVersion, use {{Values.image.tag}} instead
